# Generated by Django 5.0.2 on 2024-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='counter', max_length=50)),
                ('intensity', models.CharField(max_length=30)),
                ('voltage', models.CharField(max_length=30)),
                ('power', models.CharField(max_length=30)),
                ('energy', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
    ]
